### ISSUE TITLE
style="?android:attr/borderlessButtonStyle" 设置问题

### ISSUE THREAD

**Issue by Cenler** [niniloveyou/StateButton#12]
设置 style="?android:attr/borderlessButtonStyle" 去掉阴影后, 某些机型(华为荣耀-EMUI系统3.0-Android-4.4.2)会出现自定义属性无效, 对控件进android:background="@null"设置可以解决, 具体原因不详.

**Comment by ghost** [comment]
you can use 
style="[at]style/Widget.AppCompat.Button.Borderless" 
hope it helps.

**Comment by niniloveyou** [comment]
Okay Thank you ! @0M1D
