### ISSUE TITLE
太长了

### ISSUE THREAD

**Issue by Yanqilong** [niniloveyou/StateButton#14]
使用android:layout_width="wrap_content"宽度没有自适应，而是默认了一个值，按钮只有两个文字的情况下，太长了，我暂时采取的做法是给一个默认值固定，但感觉不好，为什么android:layout_width="wrap_content"没有自适应呢？

**Comment by niniloveyou** [comment]
android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:minHeight="20dp"
                android:minWidth="50dp"
                android:background="@null"

这个是因为继承了AppCompatButton, 系统主题所致， 如果想自适应如上所写。

**Comment by Yanqilong** [comment]
谢谢，按你说的设置后有效果
