### ISSUE TITLE
Toolbar 中，wrapContent会属性会强制拉伸到跟父容器一样高，如果设置宽高为固定dp，字显示不出来了

### ISSUE THREAD

**Issue by mrme2014** [niniloveyou/StateButton#18]
Toolbar 中，wrapContent会属性会强制拉伸到跟父容器一样高，如果设置宽高为固定dp，字显示不出来了

**Comment by niniloveyou** [comment]
你可以看看其他人提的问题，系统主题所致

**Comment by sheaye** [comment]
![qq 20170818181546](https://user-images.githubusercontent.com/26473649/29455429-ab92bbbe-8443-11e7-82e8-1c1295703007.png)
