### ISSUE TITLE
反馈StateButton BUG

### ISSUE THREAD

**Issue by tcqq** [niniloveyou/StateButton#22]
设置 android:fontFamily 后 ，预览界面中的StateButton将显示异常

**Comment by tcqq** [comment]
固定button高度的情况下，如果不设置android:padding="0dp"，按钮中的文字无法显示完整

**Comment by XuEnhao** [comment]
normalBackgroundColor 无法显示 还报错 No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.onenineoneone.a1911school-2/split_lib_dependencies_apk.apk)

**Comment by tcqq** [comment]
@XuEnhao [更好的相同类型的库](https://github.com/RuffianZhong/RTextView)

**Comment by niniloveyou** [comment]
这个只是继承AppCompatButton原生的button也是这样的，这个锅不背 @tcqq
