### ISSUE TITLE
如何把这个阴影去除

### ISSUE THREAD

**Issue by songlongkuan** [niniloveyou/StateButton#23]
![screenshot_20180512-143743](https://user-images.githubusercontent.com/16483654/39954450-50d8f8c4-55f2-11e8-87ba-9cc6469a4bb6.jpg)

**Comment by niniloveyou** [comment]
7.0及以上才会有这个问题，stateListAnimator="@null" @pencilso

**Comment by songlongkuan** [comment]
好的
