### ISSUE TITLE
按钮太大了 ， 高度设置稍微小点， 里面的字体就看不到了。

### ISSUE THREAD

**Issue by zhaoxiuyu** [niniloveyou/StateButton#3]
按钮太大了 ， 高度设置稍微小点， 里面的字体就看不到了。
![qwe](https://cloud.githubusercontent.com/assets/16554580/20384144/a46c04c2-aced-11e6-91fa-0517aba8c1a0.png)

**Comment by niniloveyou** [comment]
把xml发上来看看，完整的

**Comment by zhaoxiuyu** [comment]
@niniloveyou    

XML 很简单  就是设置 了 按钮的高度，就显示不全了，按钮内部文字的上下高度空白太大了 。
代码在下面  ： 

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

```
<com.sendinfo.maoxiaoniu.custom.StateButton
    android:layout_width="wrap_content"
    android:layout_height="30dp"
    android:text="预定"
    app:animationDuration="200"
    app:normalBackgroundColor="@color/white"
    app:normalStrokeColor="@color/SwipToGoogle_red"
    app:normalStrokeWidth="1dp"
    app:normalTextColor="@color/SwipToGoogle_red"
    app:pressedBackgroundColor="@color/SwipToGoogle_red"
    app:pressedTextColor="@android:color/white"
    app:radius="2dp" />
```

</LinearLayout>

**Comment by niniloveyou** [comment]
```
<android.support.v7.widget.AppCompatButton
    android:layout_width="wrap_content"
    android:layout_height="30dp"
    android:text="预定"/>   
```

你这样试试，也会是这样，说明系统中button主题里默认设置了padding的

**Comment by zhaoxiuyu** [comment]
@niniloveyou 

我这样试过，确实会这样，哎，这样按钮太大了。。。
我试着把这个类StateButton的继承改成 TextView，还是会自动padding。。。
你看这个能修复不，不然我要手写Selector了。。。要炸。。。
![1017](https://cloud.githubusercontent.com/assets/16554580/20415552/03f198f4-ad74-11e6-9d06-44cc9b75a782.gif)

**Comment by niniloveyou** [comment]
xml中设置padding = “0dp”就行了

**Comment by tcqq** [comment]
我不想每次都设置padding =“0dp，可以在代码里处理一下这个问题吗？
