### ISSUE TITLE
同步出错，一定要24版本的AndroidSDK吗？改成complieSDK=23,TargetSDK=22导致build.gradle内android() not found

### ISSUE THREAD

**Issue by TommyLemon** [niniloveyou/StateButton#4]
Gradle sync failed: Cause: failed to find target with hash string 'android-24' in: /Users/Tommy/Library/Android/sdk          Consult IDE log for more details (Help | Show Log)

**Comment by niniloveyou** [comment]
http://stackoverflow.com/questions/32715418/failed-to-find-target-with-hash-string-android-22
类似的问题！ 看看吧，跟控件没啥关系！

**Comment by TommyLemon** [comment]
解决了。不是这个问题。
http://stackoverflow.com/questions/27735646/android-studio-gradle-dsl-method-not-found-android-error17-0
第2个答案，删除最外层build.gradle里的android{...}。
然后还要complie androidSDK = 24, JDK = 1.8
运行成功
