### ISSUE TITLE
字体颜色变化的组件点击后变了颜色，但手离开屏幕后颜色没有还原

### ISSUE THREAD

**Issue by TommyLemon** [niniloveyou/StateButton#5]
Change text color,change background（背景）,with dash,with stroke,

**Comment by niniloveyou** [comment]
你是不是哪里设置了enable=false如果是需要设置不可用情况下的各种颜色

**Comment by TommyLemon** [comment]
没设置，也没改源码，直接用源码编译的apk😂

**Comment by niniloveyou** [comment]
我回家再验证下，刚下班

**Comment by niniloveyou** [comment]
我验证了下没这问题，不知道你那边什么情况！

**Comment by TommyLemon** [comment]
今天重新下载运行后还是有这个问题：

![screenshot_2016-12-04-20-01-14_deadline statebutt](https://cloud.githubusercontent.com/assets/5738175/20866048/9cbbd694-ba5d-11e6-84ba-6e7a3fd268de.png)
![screenshot_2016-12-04-20-12-17_com android settin](https://cloud.githubusercontent.com/assets/5738175/20866063/05f61ff2-ba5e-11e6-8e34-77486c1eb7b2.png)

![screenshot_2016-12-04-20-01-03](https://cloud.githubusercontent.com/assets/5738175/20866072/1cfb6bc6-ba5e-11e6-88b2-7b08a3d97c0e.png)
![screenshot_2016-12-04-20-11-39](https://cloud.githubusercontent.com/assets/5738175/20866075/27dda298-ba5e-11e6-9618-074f33f5ab94.png)


点击后滑动不会出现，单独点击会有。
出现这种情况时会有以下log：
12-04 20:04:08.660 12670-12670/deadline.statebutton V/AudioManager: playSoundEffect   effectType: 0
12-04 20:04:08.660 12670-12670/deadline.statebutton V/AudioManager: querySoundEffectsEnabled...

希望解决下，谢谢

**Comment by niniloveyou** [comment]
当然不还原了，设置成enable false了，你有没有看MainActivity

**Comment by TommyLemon** [comment]
确实是这样
