### ISSUE TITLE
同一个layout里放多个statebutton，点击一个，其它的状态也跟着改变。

### ISSUE THREAD

**Issue by wulong-tea** [niniloveyou/StateButton#7]
同一个layout里放多个statebutton，点击一个，其它的状态也跟着改变。

**Comment by niniloveyou** [comment]
你好好看看demo

**Comment by wulong-tea** [comment]
给statebutton的父layout设了onclicklistener但不给statebutton设onclicklistener, 它们的状态会联动。
用系统自带Button没这个问题。

**Comment by niniloveyou** [comment]
我测试了，没这问题，如果你觉得还是有问题，不妨把你的xml 和代码贴上来，我再测下！

**Comment by wulong-tea** [comment]
测试机是华为M2803L平板。貌似手机上没这问题。暂时忽略这个问题吧，按钮加上事件就没事了。

**Comment by wulong-tea** [comment]
http://pan.baidu.com/s/1qX9mQJE
