### ISSUE TITLE
如果在StateButton中设置了文字又同时设定drawableLeft，那么文字和图标有什么方法可以同时居中呢？

### ISSUE THREAD

**Issue by Lsy1992** [niniloveyou/StateButton#9]

**Comment by niniloveyou** [comment]
这跟stateButoon没有半毛钱关系，stateButton只是设置了文字颜色，至于你说的问题，应该drawablePadding属性应该就可以

**Comment by Lsy1992** [comment]
我知道没有半毛钱关系，这是Android官方对Button的一个设置，想问问你有没有办法，drawablePadding并不能准确的和文字居中在一起，会有差异

**Comment by wulong-tea** [comment]
兄弟，有人帮你测试，为毛你这么急躁？

**Comment by Lsy1992** [comment]
该不会是说我吧?...( ⊙ o ⊙ )

**Comment by niniloveyou** [comment]
不是急躁，说话直习惯了，不要放在心上！
